// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eslwhkmlwlmiuxoxuskf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbHdoa21sd2xtaXV4b3h1c2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzc3MzIsImV4cCI6MjA1OTcxMzczMn0.yfY1J6vUyoi6SEX7d4tRO97fJ18moQ_CIy-HjfuZrsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);